### ISSUE TITLE
HTML object is downloaded

### ISSUE THREAD

**Issue by tommydino93** [nsadawi/Download-Large-File-From-Google-Drive-Using-Python#2]
Hi!
I'm trying to download a .nii (nifti) volume from a Drive folder, but even if I specify

`destination = '/my/path/volume.nii'`

the downloaded file is a HTML object and not a nifti volume anymore.

What could I try?
Thanks in advance!

**Comment by nsadawi** [comment]
Hi .. please send me the link to the file and I'll test on my machine!

**Comment by tommydino93** [comment]
Sure, here it is: https://drive.google.com/open?id=19lltZ5pD4J8foN3MxpmtiRWPyaD0NIlp

**Comment by nsadawi** [comment]
This works fine here:
`file_id = '19lltZ5pD4J8foN3MxpmtiRWPyaD0NIlp'`
`destination = 'myfile.nii'`
`download_file_from_google_drive(file_id, destination)`

**Comment by tommydino93** [comment]
You are right! I was using the last part of the link, instead of the id of the shareable link. I thought they were the same.

Thank you very much!

**Comment by tommydino93** [comment]
Hi @nsadawi!

Sorry to re-open this, but I have now a problem with the following file:

https://drive.google.com/file/d/12TMJZ_9SmrDzJJys2d8i_cO3D-OsNPuw/view?usp=sharing

In the python script I wrote:

`file_id = '12TMJZ_9SmrDzJJys2d8i_cO3D-OsNPuw'`
`destination = 'my_file_t2.nii'`
`download_file_from_google_drive(file_id, destination)`

but this downloads a corrupted file which I cannot use afterwards.

What could be the problem?

Thanks again!

**Comment by nsadawi** [comment]
Are you sure the file is publicly shared? .. i.e. did you get the link by doing share -> get shareable link

**Comment by tommydino93** [comment]
Mm no, I copied the URL. Now I turned linked sharing on and the link I get is again:

https://drive.google.com/file/d/12TMJZ_9SmrDzJJys2d8i_cO3D-OsNPuw/view?usp=drivesdk

**Comment by nsadawi** [comment]
Yes when file sharing is turned on it will download correctly!
It makes sense right? you want others to download your file so you share it with them first!

**Comment by tommydino93** [comment]
Yes, you are right. It's now working correctly.

Thanks again!
